# Generated by Django 5.1.3 on 2024-11-11 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Years",
            fields=[
                (
                    "year",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PopulationAndDemography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(blank=True, max_length=100, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.years",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliticalRegieme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(blank=True, max_length=100, null=True)),
                ("political_regime", models.IntegerField(blank=True, null=True)),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.years",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrudeBirthRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_rate", models.IntegerField(blank=True, null=True)),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.years",
                    ),
                ),
            ],
        ),
    ]
