# Generated by Django 5.1.3 on 2024-11-11 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReligiousLarge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(blank=True, max_length=100, null=True)),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                ("group_proportion", models.IntegerField(blank=True, null=True)),
                ("group_estimate", models.IntegerField(blank=True, null=True)),
                ("outlier", models.IntegerField(blank=True, null=True)),
                ("anchor", models.IntegerField(blank=True, null=True)),
                ("independent_country", models.BooleanField(blank=True, null=True)),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.years",
                    ),
                ),
            ],
        ),
    ]
