# Generated by Django 5.1.3 on 2024-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_religiouslarge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crudebirthrate",
            name="birth_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="religiouslarge",
            name="group_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="religiouslarge",
            name="group_proportion",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
